# This is a basic workflow to help you get started with Actions

name: Tado Terraform Apply

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: hashicorp/terraform:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: terraform init
        run: terraform init
        working-directory: ./
      
      # Runs a single command using the runners shell
      - name: terraform apply
        run: |
          terraform apply -var="tado_username=${{ secrets.TADO_USERNAME }}" -var="tado_passord=${{ secrets.TADO_PASSWORD }}" -auto-approve
        working-directory: ./
